source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '7.1'

pod 'PSPDFKit', '4.1'
pod 'AFNetworking', '2.4.1'
pod 'REFrostedViewController', '2.4.7'
pod 'JDStatusBarNotification', '1.4.9'
pod 'UIActionSheet+Blocks', '0.8.1'
pod 'GoogleAnalytics-iOS-SDK', '3.10'
pod 'KVNProgress', '2.1.6'
pod 'Lockbox', '2.1.0'
